apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
  - port: 2181
    targetPort: 2181
    nodePort: 2181
    protocol: TCP
  selector:
    app: zookeeper-app
  type: NodePort
